[[constraint]]
  name = "github.com/cloudfoundry-community/go-cfenv"
  version = "1.17.0"

[[constraint]]
  name = "github.com/bgentry/que-go"
  source = "github.com/govau/que-go"
  branch = "fixshutdown"

[prune]
  go-tests = true
  unused-packages = true
